name: AI Analyzer

on:
  issues:
    types: [labeled]
  workflow_dispatch: {}

jobs:
  analyze:
    if: |
      (github.event_name == 'issues' &&
       github.event.action == 'labeled' &&
       github.event.label.name == 'bot:analyze') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: analyzer-${{ github.event.issue.number }}
      cancel-in-progress: true
    permissions:
      contents: read
      issues: write
      pull-requests: read
      repository-projects: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt
          fi

          if [ -f .github/agents/requirements.txt ]; then 
            pip install -r .github/agents/requirements.txt
          else
            pip install httpx openai anthropic google-generativeai
          fi

      - name: Run analyzer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_CLASSIC_TOKEN: ${{ secrets.GH_CLASSIC_TOKEN }}
          GH_PROJECT_ID: ${{ secrets.GH_PROJECT_ID }}
          GITHUB_PROJECT_ID: ${{ secrets.GH_PROJECT_ID }}
          PROJECT_STATUS_FIELD_ID: ${{ secrets.PROJECT_STATUS_FIELD_ID }}
          PROJECT_STATUS_BACKLOG_ID: ${{ secrets.PROJECT_STATUS_BACKLOG_ID }}
          PROJECT_STATUS_INPROGRESS_ID: ${{ secrets.PROJECT_STATUS_INPROGRESS_ID }}
          PROJECT_STATUS_INREVIEW_ID: ${{ secrets.PROJECT_STATUS_INREVIEW_ID }}
          PROJECT_STATUS_DONE_ID: ${{ secrets.PROJECT_STATUS_DONE_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python .github/agents/analyzer.py

