name: AI Developer

on:
  # Issue mode: labeled with bot:implement
  issues:
    types: [labeled]

  # PR-fix mode: labeled with need-fix OR new commits
  pull_request:
    types: [labeled, synchronize]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  dev-issue:
    if: github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'bot:implement'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install httpx openai anthropic google-generativeai
      - name: Configure git
        run: |
          git config --global user.name "AI Developer"
          git config --global user.email "ai-dev@users.noreply.github.com"
      - name: Run Developer (Issue Mode)
        run: python .github/agents/dev.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_CLASSIC_TOKEN: ${{ secrets.GH_CLASSIC_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DEVELOPER_MODEL: ${{ vars.DEVELOPER_MODEL || 'gpt-4o-mini' }}

  dev-pr-fix:
    if: >
      github.event_name == 'pull_request' && (
        (github.event.action == 'labeled' && github.event.label.name == 'need-fix') ||
        github.event.action == 'synchronize'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_CLASSIC_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install httpx openai anthropic google-generativeai
      - name: Configure git (CRITICAL for commits)
        run: |
          git config --global user.name "AI Developer"
          git config --global user.email "ai-dev@users.noreply.github.com"
      - name: Run Developer (PR-fix Mode)
        run: python .github/agents/dev.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CLASSIC_TOKEN }}
          GH_CLASSIC_TOKEN: ${{ secrets.GH_CLASSIC_TOKEN }}
          GH_PROJECT_ID: ${{ secrets.GH_PROJECT_ID }}
          GITHUB_PROJECT_ID: ${{ secrets.GH_PROJECT_ID }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DEVELOPER_MODEL: ${{ vars.DEVELOPER_MODEL || 'gpt-4o-mini' }}


           