name: AI Developer
permissions:
  contents: write
  pull-requests: write
  issues: read
on:
  issues:
    types: [labeled]

concurrency:
  group: dev-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  implement:
    if: contains(toJson(github.event.issue.labels), 'bot:implement')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure Git identity
        run: |
          git config user.name "ai-dev-bot"
          git config user.email "ai-dev-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git remote -v

      - name: Install dependencies
        run: pip install httpx openai anthropic google-generativeai

      - name: Run AI Developer
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CLASSIC_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # Projects v2 (facoltativi ma consigliati)
          GITHUB_PROJECT_ID: ${{ secrets.GH_PROJECT_ID }}
          PROJECT_STATUS_FIELD_ID: ${{ secrets.PROJECT_STATUS_FIELD_ID }}
          PROJECT_STATUS_BACKLOG_ID: ${{ secrets.PROJECT_STATUS_BACKLOG_ID }}
          PROJECT_STATUS_INPROGRESS_ID: ${{ secrets.PROJECT_STATUS_INPROGRESS_ID }}
          PROJECT_STATUS_INREVIEW_ID: ${{ secrets.PROJECT_STATUS_INREVIEW_ID }}
          PROJECT_STATUS_DONE_ID: ${{ secrets.PROJECT_STATUS_DONE_ID }}
          # Dati dell’issue
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          REPO: ${{ github.repository }}
        run: python .github/agents/analyzer.py


        