name: dev-fix

on:
  # Avvio manuale con input PR (comodo per test)
  workflow_dispatch:
    inputs:
      pr:
        description: "PR number to fix"
        required: true
        type: number
  # Avvio automatico: parte quando si aggiunge una label al PR
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: dev-fix-${{ github.event.pull_request.number || inputs.pr || github.run_id }}
  cancel-in-progress: true

jobs:
  run-dev-fix:
    # Parte se lanci manualmente OPPURE quando la label aggiunta è esattamente "need-rewiew"
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.label.name == 'need-rewiew' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Dev (PR Fix Mode)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_CLASSIC_TOKEN: ${{ secrets.GH_CLASSIC_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr }}
          REFACE_STRATEGY: full
        run: |
          echo "🔧 PR Fix for #${PR_NUMBER}"
          python .github/agents/dev.py --mode fix --pr ${PR_NUMBER}

      # Step diagnostico utile quando fallisce il preflight (facoltativo ma consigliato)
      - name: Debug current file snapshot
        if: failure() || always()
        run: |
          echo "=== HEAD:projects/math_utils.py (first 60 lines) ==="
          git --no-pager show HEAD:projects/math_utils.py | nl -ba | sed -n '1,60p'
